name: sequence
on:
  push:
    branches:
      - sequence

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: lire
        run: echo "BUILD"

  TEST_APP:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: lire_1
        run: echo "TEST_APP"

  TEST_API:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: lire_2
        run: echo "TEST_API"

  DEPLOY:
    runs-on: ubuntu-latest
    needs: [TEST_APP, TEST_API]
    steps:
      - name: lire_3
        run: echo "DEPLOY"

  NOTIFY_TEST_FAILURE:
    runs-on: ubuntu-latest
    needs: [TEST_APP, TEST_API]
    if: ${ { failure() } }
    steps:
      - name: lire_4
        run: echo "TEST FAILED"
